package bootstrap 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Mysql struct {

	/*GaleraHealthcheck - Descr: Port used by sidecar process to listen on Default: 9200
*/
	GaleraHealthcheck *GaleraHealthcheck `yaml:"galera_healthcheck,omitempty"`

	/*ClusterIps - Descr: IP addresses of all MySQL nodes Default: <nil>
*/
	ClusterIps interface{} `yaml:"cluster_ips,omitempty"`

	/*DatabaseStartupTimeout - Descr: Maximum time to transition to or from a stopped or started state before we timeout. Default: <nil>
*/
	DatabaseStartupTimeout interface{} `yaml:"database_startup_timeout,omitempty"`

}