package broker_deregistrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Broker struct {

	/*Services - Descr: List of services the broker provides Default: <nil>
*/
	Services interface{} `yaml:"services,omitempty"`

}