package broker_deregistrar 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*Broker - Descr: List of services the broker provides Default: <nil>
*/
	Broker *Broker `yaml:"broker,omitempty"`

}