package etcd_testconsumer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdTestconsumerJob struct {

	/*EtcdTestconsumer - Descr: Addresses of etcd machines Default: <nil>
*/
	EtcdTestconsumer *EtcdTestconsumer `yaml:"etcd_testconsumer,omitempty"`

}