package etcd_testconsumer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdTestconsumer struct {

	/*Etcd - Descr: Addresses of etcd machines Default: <nil>
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

}