package collector 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CollectorJob struct {

	/*Nats - Descr: NATS password Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*Collector - Descr: enable CloudWatch plugin Default: false
*/
	Collector *Collector `yaml:"collector,omitempty"`

}