package tps 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Capi struct {

	/*Tps - Descr: address at which to serve debug info Default: 0.0.0.0:17014
*/
	Tps *Tps `yaml:"tps,omitempty"`

}