package tps 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TpsJob struct {

	/*Capi - Descr: address at which to serve debug info Default: 0.0.0.0:17014
*/
	Capi *Capi `yaml:"capi,omitempty"`

	/*Diego - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Diego *Diego `yaml:"diego,omitempty"`

}