package replication_canary 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*ExternalHost - Descr: Domain of the route registered for the UI via NATS (with the router in cf-release) Default: <nil>
*/
	ExternalHost interface{} `yaml:"external_host,omitempty"`

}