package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AcceptanceTests struct {

	/*Registry - Descr: Password for the BOSH registry Default: password
*/
	Registry *Registry `yaml:"registry,omitempty"`

	/*ConsulReleaseVersion - Descr: The default consul-release version number to deploy Default: latest
*/
	ConsulReleaseVersion interface{} `yaml:"consul_release_version,omitempty"`

	/*Aws - Descr: Region for AWS deployments Default: us-east-1
*/
	Aws *Aws `yaml:"aws,omitempty"`

	/*ParallelNodes - Descr: Number of parallel nodes to use for tests Default: 1
*/
	ParallelNodes interface{} `yaml:"parallel_nodes,omitempty"`

	/*Bosh - Descr: BOSH Director CA Cert Default: 
*/
	Bosh *Bosh `yaml:"bosh,omitempty"`

}