package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AcceptanceTestsJob struct {

	/*Consul - Descr: Password for the BOSH registry Default: password
*/
	Consul *Consul `yaml:"consul,omitempty"`

}