package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AcceptanceTestsJob struct {

	/*AcceptanceTests - Descr: Default Timeout Default: <nil>
*/
	AcceptanceTests *AcceptanceTests `yaml:"acceptance_tests,omitempty"`

}