package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Aws struct {

	/*DefaultSecurityGroups - Descr: Security groups for AWS deployments Default: []
*/
	DefaultSecurityGroups interface{} `yaml:"default_security_groups,omitempty"`

	/*Subnets - Descr: Subnet ID for AWS deployments Default: 
*/
	Subnets interface{} `yaml:"subnets,omitempty"`

	/*AccessKeyId - Descr: Key ID for AWS deployments Default: 
*/
	AccessKeyId interface{} `yaml:"access_key_id,omitempty"`

	/*DefaultKeyName - Descr: Default Key Name for AWS deployments Default: bosh
*/
	DefaultKeyName interface{} `yaml:"default_key_name,omitempty"`

	/*Region - Descr: Region for AWS deployments Default: us-east-1
*/
	Region interface{} `yaml:"region,omitempty"`

	/*SecretAccessKey - Descr: Secret Access Key for AWS deployments Default: 
*/
	SecretAccessKey interface{} `yaml:"secret_access_key,omitempty"`

}