package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Bosh struct {

	/*Password - Descr: BOSH Director password Default: admin
*/
	Password interface{} `yaml:"password,omitempty"`

	/*DirectorCaCert - Descr: BOSH Director CA Cert Default: 
*/
	DirectorCaCert interface{} `yaml:"director_ca_cert,omitempty"`

	/*Target - Descr: Location of the BOSH Director to target when deploying consul Default: 192.168.50.4
*/
	Target interface{} `yaml:"target,omitempty"`

	/*Username - Descr: BOSH Director username Default: admin
*/
	Username interface{} `yaml:"username,omitempty"`

}