package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*AcceptanceTests - Descr: scaling multiplier used to determine command timeouts Default: 1
*/
	AcceptanceTests *AcceptanceTests `yaml:"acceptance_tests,omitempty"`

	/*Proxy - Descr: Proxy API password Default: <nil>
*/
	Proxy *Proxy `yaml:"proxy,omitempty"`

	/*ExternalHost - Descr: Hostname given for dashboard URLs (e.g. p-mysql.example.com) Default: <nil>
*/
	ExternalHost interface{} `yaml:"external_host,omitempty"`

	/*Mysql - Descr: Admin username used to access MySQL Default: root
*/
	Mysql *Mysql `yaml:"mysql,omitempty"`

	/*Host - Descr: Hostname given to apps by the broker, usually a Load Balancer address or the IP of the first proxy Default: <nil>
*/
	Host interface{} `yaml:"host,omitempty"`

	/*Broker - Descr: Array of Services the broker provides Default: <nil>
*/
	Broker *Broker `yaml:"broker,omitempty"`

}