package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Consul struct {

	/*AcceptanceTests - Descr: Password for the BOSH registry Default: password
*/
	AcceptanceTests *AcceptanceTests `yaml:"acceptance_tests,omitempty"`

}