package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Registry struct {

	/*Username - Descr: Username for the BOSH registry Default: admin
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Host - Descr: Host for the BOSH registry Default: 127.0.0.1
*/
	Host interface{} `yaml:"host,omitempty"`

	/*Port - Descr: Port for the BOSH registry Default: 25777
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Password - Descr: Password for the BOSH registry Default: password
*/
	Password interface{} `yaml:"password,omitempty"`

}