package destroy_notifications_ui 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cf struct {

	/*AdminUser - Descr: Username of the CF admin user Default: <nil>
*/
	AdminUser interface{} `yaml:"admin_user,omitempty"`

	/*AdminPassword - Descr: Password of the CF admin user Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

	/*DialTimeout - Descr: CF CLI connection dial timeout Default: 5
*/
	DialTimeout interface{} `yaml:"dial_timeout,omitempty"`

}