package destroy_notifications_ui 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DestroyNotificationsUiJob struct {

	/*Domain - Descr: Cloud Foundry System Domain Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

	/*NotificationsUi - Descr: Space where the app is deployed Default: <nil>
*/
	NotificationsUi *NotificationsUi `yaml:"notifications_ui,omitempty"`

	/*Ssl - Descr: Whether to verify SSL certs when making web requests Default: <nil>
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}