package rep_windows 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Rep - Descr: PEM-encoded client certificate Default: <nil>
*/
	Rep *Rep `yaml:"rep,omitempty"`

	/*Executor - Descr: Maximum number of concurrent create container operations. Default: 32
*/
	Executor *Executor `yaml:"executor,omitempty"`

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}