package test_autoscaling 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Autoscale struct {

	/*Cf - Descr: Password of the CF admin user Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

}