package consul_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ConsulAgentJob struct {

	/*Consul - Descr: A list of passphrases that will be converted into encryption keys, the first key in the list is the active one Default: <nil>
*/
	Consul *Consul `yaml:"consul,omitempty"`

}