package nsync 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Capi struct {

	/*Nsync - Descr: External Cloud Controller port Default: 9022
*/
	Nsync *Nsync `yaml:"nsync,omitempty"`

}