package arbitrator 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ArbitratorJob struct {

	/*CfMysql - Descr: Username used by the sidecar endpoints for Basic Auth Default: <nil>
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

}