package routing_api 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Consul struct {

	/*Servers - Descr: comma-separated list of consul server URLs (scheme://ip:port) Default: http://127.0.0.1:8500
*/
	Servers interface{} `yaml:"servers,omitempty"`

}