package routing_api 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Etcd struct {

	/*Servers - Descr: Must be the internal DNS name for the etcd cluster when require_ssl:true. When require_ssl:false either a DNS name or an array of IP addresses is supported. Default: <nil>
*/
	Servers interface{} `yaml:"servers,omitempty"`

	/*RequireSsl - Descr: etcd requires client to communicate via TLS Default: false
*/
	RequireSsl interface{} `yaml:"require_ssl,omitempty"`

	/*CaCert - Descr: Certificate authority used to sign cert hosted by etcd Default: 
*/
	CaCert interface{} `yaml:"ca_cert,omitempty"`

	/*ClientCert - Descr: Client certificate for communication between clients and etcd Default: 
*/
	ClientCert interface{} `yaml:"client_cert,omitempty"`

	/*ClientKey - Descr: Client key for communication between clients and etcd Default: 
*/
	ClientKey interface{} `yaml:"client_key,omitempty"`

}