package routing_api 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RoutingApi struct {

	/*Etcd - Descr: Client key for communication between clients and etcd Default: 
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

	/*MetricsReportingInterval - Descr: String representing interval for reporting the following metrics: total_http_subscriptions, total_http_routes, total_tcp_subscriptions, total_tcp_routes, total_token_errors, key_refresh_events. Units: ms, s, m h Default: 30s
*/
	MetricsReportingInterval interface{} `yaml:"metrics_reporting_interval,omitempty"`

	/*MaxTtl - Descr: String representing the maximum TTL a client can request for route registration. Default: 120s
*/
	MaxTtl interface{} `yaml:"max_ttl,omitempty"`

	/*AuthDisabled - Descr: Disables UAA authentication Default: false
*/
	AuthDisabled interface{} `yaml:"auth_disabled,omitempty"`

	/*RouterGroups - Descr: Array of router groups that will be seeded into routing_api database. Once some value is included with a deploy, subsequent changes to this property will be ignored. TCP Routing requires a router group of type: tcp. Default: []
*/
	RouterGroups interface{} `yaml:"router_groups,omitempty"`

	/*StatsdClientFlushInterval - Descr: Buffered statsd client flush interval Default: 300ms
*/
	StatsdClientFlushInterval interface{} `yaml:"statsd_client_flush_interval,omitempty"`

	/*LogLevel - Descr: Log level Default: info
*/
	LogLevel interface{} `yaml:"log_level,omitempty"`

	/*Sqldb - Descr: Password used for connecting to SQL database Default: <nil>
*/
	Sqldb *Sqldb `yaml:"sqldb,omitempty"`

	/*StatsdEndpoint - Descr: The endpoint for the statsd server used to translate the following metrics from statsd to dropsonde: total_http_subscriptions, total_http_routes, total_tcp_subscriptions, total_tcp_routes, total_token_errors, key_refresh_events. Default: localhost:8125
*/
	StatsdEndpoint interface{} `yaml:"statsd_endpoint,omitempty"`

	/*DebugAddress - Descr: Address at which to serve debug info Default: 0.0.0.0:17002
*/
	DebugAddress interface{} `yaml:"debug_address,omitempty"`

	/*LockRetryInterval - Descr: interval to wait before retrying a failed lock acquisition Default: 5s
*/
	LockRetryInterval interface{} `yaml:"lock_retry_interval,omitempty"`

	/*LockTtl - Descr: TTL for service lock Default: 10s
*/
	LockTtl interface{} `yaml:"lock_ttl,omitempty"`

	/*SystemDomain - Descr: Domain reserved for CF operator; base URL where the UAA, Cloud Controller, and other non-user apps listen Default: <nil>
*/
	SystemDomain interface{} `yaml:"system_domain,omitempty"`

}