package routing_api 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Sqldb struct {

	/*Username - Descr: Username used for connecting to SQL database Default: <nil>
*/
	Username interface{} `yaml:"username,omitempty"`

	/*Password - Descr: Password used for connecting to SQL database Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

	/*Type - Descr: Type of SQL database Default: <nil>
*/
	Type interface{} `yaml:"type,omitempty"`

	/*Host - Descr: Host for SQL database Default: <nil>
*/
	Host interface{} `yaml:"host,omitempty"`

	/*Port - Descr: Port on which SQL database is listening Default: <nil>
*/
	Port interface{} `yaml:"port,omitempty"`

	/*Schema - Descr: Database name for routing api Default: <nil>
*/
	Schema interface{} `yaml:"schema,omitempty"`

}