package routing_api 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Uaa struct {

	/*TlsPort - Descr: Port on which UAA is listening for TLS connections. This is required for obtaining a key to verify client OAuth tokens. Default: <nil>
*/
	TlsPort interface{} `yaml:"tls_port,omitempty"`

	/*CaCert - Descr: Certificate authority for communication between clients and UAA. Default: 
*/
	CaCert interface{} `yaml:"ca_cert,omitempty"`

}