package route_emitter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*RouteEmitter - Descr: Interval to sync routes to the router in seconds. Default: 60
*/
	RouteEmitter *RouteEmitter `yaml:"route_emitter,omitempty"`

}