package route_emitter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RouteEmitterJob struct {

	/*Diego - Descr: Interval to sync routes to the router in seconds. Default: 60
*/
	Diego *Diego `yaml:"diego,omitempty"`

}