package deploy_notifications_ui 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Uaa struct {

	/*ClientId - Descr: ID of the notifications-ui UAA client Default: <nil>
*/
	ClientId interface{} `yaml:"client_id,omitempty"`

	/*ClientSecret - Descr: Secret of the notifications-ui UAA client Default: <nil>
*/
	ClientSecret interface{} `yaml:"client_secret,omitempty"`

}