package doppler 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DopplerEtcd struct {

	/*ClientKey - Descr: PEM-encoded client key Default: 
*/
	ClientKey interface{} `yaml:"client_key,omitempty"`

	/*ClientCert - Descr: PEM-encoded client certificate Default: 
*/
	ClientCert interface{} `yaml:"client_cert,omitempty"`

}