package test_notifications 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TestNotificationsJob struct {

	/*Notifications - Descr: Password of the CF admin user Default: <nil>
*/
	Notifications *Notifications `yaml:"notifications,omitempty"`

	/*Domain - Descr: Cloud Foundry System Domain Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

}