package cfdot 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfdotJob struct {

	/*Diego - Descr: PEM-encoded CA certificate Default: <nil>
*/
	Diego *Diego `yaml:"diego,omitempty"`

}