package cfdot 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cfdot struct {

	/*Bbs - Descr: PEM-encoded CA certificate Default: <nil>
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

}