package cfdot 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Cfdot - Descr: PEM-encoded CA certificate Default: <nil>
*/
	Cfdot *Cfdot `yaml:"cfdot,omitempty"`

}