package cc_uploader 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Capi struct {

	/*CcUploader - Descr: local metron agent's port Default: 3457
*/
	CcUploader *CcUploader `yaml:"cc_uploader,omitempty"`

}