package uaa 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type UaaJob struct {

	/*Login - Descr: SMTP from address Default: <nil>
*/
	Login *Login `yaml:"login,omitempty"`

	/*Env - Descr: The http_proxy across the VMs used for all requests over http Default: <nil>
*/
	Env *Env `yaml:"env,omitempty"`

	/*Uaa - Descr: Set to true to enable LDAP Default: false
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

	/*Uaadb - Descr: The list of databases used in UAA database including tag/name Default: <nil>
*/
	Uaadb *Uaadb `yaml:"uaadb,omitempty"`

}