package garden 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type GardenJob struct {

	/*Garden - Descr: If true, all existing containers will be destroyed any time the garden server starts up Default: false
*/
	Garden *Garden `yaml:"garden,omitempty"`

}