package cf_mysql_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*Mysql - Descr: Username for the admin MySQL account Default: root
*/
	Mysql *Mysql `yaml:"mysql,omitempty"`

	/*Host - Descr: Host (DNS) or IP address used by the broker and bound applications to reach the service Default: <nil>
*/
	Host interface{} `yaml:"host,omitempty"`

	/*Broker - Descr: Determines use of https in dashboard url and in callback uri for calls to UAA Default: true
*/
	Broker *Broker `yaml:"broker,omitempty"`

	/*ExternalHost - Descr: Host used to register a route for the broker with the router in cf-release via NATS. By registering the broker with Cloud Foundry using this route, and using the router for load balancing, the broker can be horizontally scaled. Domain is typically the same as system domain in cf-release. Default: <nil>
*/
	ExternalHost interface{} `yaml:"external_host,omitempty"`

}