package cf_mysql_broker 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysqlBrokerJob struct {

	/*CfMysql - Descr: Determines use of https in dashboard url and in callback uri for calls to UAA Default: true
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

	/*SyslogAggregator - Descr: TCP port of syslog aggregator Default: <nil>
*/
	SyslogAggregator *SyslogAggregator `yaml:"syslog_aggregator,omitempty"`

	/*Nats - Descr: Username for broker to register a route with NATS Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*Cf - Descr: Determines whether dashboard verifies SSL certificates when communicating with Cloud Controller and UAA Default: false
*/
	Cf *Cf `yaml:"cf,omitempty"`

}