package router_configurer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RouterConfigurer struct {

	/*DebugAddress - Descr: Address at which to serve debug info Default: 0.0.0.0:17002
*/
	DebugAddress interface{} `yaml:"debug_address,omitempty"`

	/*TcpStatsCollectionInterval - Descr: String representing interval for collecting statistic metrics from tcp proxy. Units: ms, s, m h Default: 1m
*/
	TcpStatsCollectionInterval interface{} `yaml:"tcp_stats_collection_interval,omitempty"`

	/*OauthSecret - Descr: OAuth client secret used to obtain token for Routing API from UAA. Default: <nil>
*/
	OauthSecret interface{} `yaml:"oauth_secret,omitempty"`

	/*LogLevel - Descr: Log level Default: info
*/
	LogLevel interface{} `yaml:"log_level,omitempty"`

}