package router_configurer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RoutingApi struct {

	/*AuthDisabled - Descr: When false, Routing API requires OAuth tokens for authentication. Default: false
*/
	AuthDisabled interface{} `yaml:"auth_disabled,omitempty"`

}