package haproxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type HaproxyJob struct {

	/*Haproxy - Descr: Load balancer in front of TCP Routers should be configured to check the health of TCP Router instances by establishing a TCP connection on this port Default: 80
*/
	Haproxy *Haproxy `yaml:"haproxy,omitempty"`

}