package haproxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Haproxy struct {

	/*RequestTimeoutInSeconds - Descr: Server and client timeouts in seconds Default: 300
*/
	RequestTimeoutInSeconds interface{} `yaml:"request_timeout_in_seconds,omitempty"`

	/*HealthCheckPort - Descr: Load balancer in front of TCP Routers should be configured to check the health of TCP Router instances by establishing a TCP connection on this port Default: 80
*/
	HealthCheckPort interface{} `yaml:"health_check_port,omitempty"`

}