package test_notifications_ui 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TestNotificationsUiJob struct {

	/*NotificationsUi - Descr: Notifications organization Default: <nil>
*/
	NotificationsUi *NotificationsUi `yaml:"notifications_ui,omitempty"`

	/*Domain - Descr: Cloud Foundry System Domain Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

}