package deploy_autoscaling 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type DeployAutoscalingJob struct {

	/*Autoscale - Descr: Base64 encoded image for marketplace registration Default: <nil>
*/
	Autoscale *Autoscale `yaml:"autoscale,omitempty"`

	/*AppDomains - Descr: CloudFoundry application domains Default: <nil>
*/
	AppDomains interface{} `yaml:"app_domains,omitempty"`

	/*Domain - Descr: CloudFoundry system domain Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

	/*Ssl - Descr: Whether to verify SSL certs when making web requests Default: <nil>
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*Uaa - Descr: UAA Client Secret Default: <nil>
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

}