package stager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Capi struct {

	/*Stager - Descr: URL of file server Default: http://file-server.service.cf.internal:8080
*/
	Stager *Stager `yaml:"stager,omitempty"`

}