package stager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StagerJob struct {

	/*Capi - Descr: URL of cc uploader Default: http://cc-uploader.service.cf.internal:9090
*/
	Capi *Capi `yaml:"capi,omitempty"`

	/*Diego - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Diego *Diego `yaml:"diego,omitempty"`

}