package stager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StagerJob struct {

	/*Capi - Descr: URL of file server Default: http://file-server.service.cf.internal:8080
*/
	Capi *Capi `yaml:"capi,omitempty"`

	/*Diego - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Diego *Diego `yaml:"diego,omitempty"`

}