package proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*Proxy - Descr: Timeout (milliseconds) before assuming a backend is unhealthy Default: 5000
*/
	Proxy *Proxy `yaml:"proxy,omitempty"`

	/*Standalone - Descr: Standalone Mode: Are you deploying MySQL without a CloudFoundry deployment? Default: false
*/
	Standalone interface{} `yaml:"standalone,omitempty"`

	/*Mysql - Descr: List of nodes.  Must have the same number of ips as there are nodes in the cluster Default: <nil>
*/
	Mysql *Mysql `yaml:"mysql,omitempty"`

	/*ExternalHost - Descr: Domain of the route registered for the UI via NATS (with the router in cf-release) Default: <nil>
*/
	ExternalHost interface{} `yaml:"external_host,omitempty"`

}