package proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ProxyJob struct {

	/*CfMysql - Descr: Timeout (milliseconds) before assuming a backend is unhealthy Default: 5000
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

	/*SyslogAggregator - Descr: Transport to be used when forwarding logs (tcp|udp|relp). Default: tcp
*/
	SyslogAggregator *SyslogAggregator `yaml:"syslog_aggregator,omitempty"`

	/*Nats - Descr: IP of each NATS cluster member. Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

}