package cloud_controller_ng 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Clients struct {

	/*CcServiceBrokerClient - Descr: (DEPRECATED) - Used for generating SSO clients for service brokers. Default: <nil>
*/
	CcServiceBrokerClient *CcServiceBrokerClient `yaml:"cc_service_broker_client,omitempty"`

	/*CcRouting - Descr: Used for fetching routing information from the Routing API Default: <nil>
*/
	CcRouting *CcRouting `yaml:"cc_routing,omitempty"`

	/*CloudControllerUsernameLookup - Descr: Used for fetching usernames from UAA. Default: <nil>
*/
	CloudControllerUsernameLookup *CloudControllerUsernameLookup `yaml:"cloud_controller_username_lookup,omitempty"`

	/*CcServiceDashboards - Descr: Used to grant scope for SSO clients for service brokers Default: openid,cloud_controller_service_permissions.read
*/
	CcServiceDashboards *CcServiceDashboards `yaml:"cc-service-dashboards,omitempty"`

}