package tcp_emitter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Bbs struct {

	/*ApiLocation - Descr: Diego BBS Server endpoint URL. Default: http://bbs.service.cf.internal:8889
*/
	ApiLocation interface{} `yaml:"api_location,omitempty"`

	/*RequireSsl - Descr: Enables mutual-TLS communication with Diego BBS. Default: true
*/
	RequireSsl interface{} `yaml:"require_ssl,omitempty"`

	/*CaCert - Descr: PEM-encoded CA certificate used to sign TLS certificate hosted by Diego BBS. Default: <nil>
*/
	CaCert interface{} `yaml:"ca_cert,omitempty"`

}