package tcp_emitter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RoutingApi struct {

	/*AuthDisabled - Descr: auth disabled setting of routing api Default: false
*/
	AuthDisabled interface{} `yaml:"auth_disabled,omitempty"`

}