package tcp_emitter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TcpEmitterBbs struct {

	/*ClientKey - Descr: PEM-encoded client key Default: <nil>
*/
	ClientKey interface{} `yaml:"client_key,omitempty"`

	/*ClientCert - Descr: PEM-encoded client certificate Default: <nil>
*/
	ClientCert interface{} `yaml:"client_cert,omitempty"`

}