package tcp_emitter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TcpEmitterJob struct {

	/*Metron - Descr: The port used to emit dropsonde messages to the Metron agent. Default: 3457
*/
	Metron *Metron `yaml:"metron,omitempty"`

	/*TcpEmitter - Descr: Password for UAA client for tcp emitter. Default: <nil>
*/
	TcpEmitter *TcpEmitter `yaml:"tcp_emitter,omitempty"`

	/*Bbs - Descr: PEM-encoded CA certificate used to sign TLS certificate hosted by Diego BBS. Default: <nil>
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

	/*Consul - Descr: comma-separated list of consul server URLs (scheme://ip:port) Default: http://127.0.0.1:8500
*/
	Consul *Consul `yaml:"consul,omitempty"`

	/*Uaa - Descr: Port on which UAA is listening for TLS connections. This is required for obtaining a OAuth token for Routing API. Default: <nil>
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

	/*SkipSslValidation - Descr: Skip TLS verification when talking to UAA Default: false
*/
	SkipSslValidation interface{} `yaml:"skip_ssl_validation,omitempty"`

	/*DnsHealthCheckHost - Descr: Host to ping for confirmation of DNS resolution Default: consul.service.cf.internal
*/
	DnsHealthCheckHost interface{} `yaml:"dns_health_check_host,omitempty"`

	/*RoutingApi - Descr: auth disabled setting of routing api Default: false
*/
	RoutingApi *RoutingApi `yaml:"routing_api,omitempty"`

}