package bbs 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type BbsJob struct {

	/*Diego - Descr: Whether to require SSL for BBS communication to the SQL backend Default: false
*/
	Diego *Diego `yaml:"diego,omitempty"`

}