package bbs 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Bbs - Descr: Whether to require SSL for BBS communication to the SQL backend Default: false
*/
	Bbs *Bbs `yaml:"bbs,omitempty"`

}