package streaming_mysql_backup_client 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type StreamingMysqlBackupClientJob struct {

	/*CfMysqlBackup - Descr: Password used by backup client to stream a backup from the mysql node Default: <nil>
*/
	CfMysqlBackup *CfMysqlBackup `yaml:"cf-mysql-backup,omitempty"`

	/*CfMysql - Descr: List of IP address of servers which can generate backups Default: <nil>
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

}