package auctioneer 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Auctioneer - Descr: address where auctioneer listens for LRP and task start auction requests Default: 0.0.0.0:9016
*/
	Auctioneer *Auctioneer `yaml:"auctioneer,omitempty"`

}