package service_backup 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Destination struct {

	/*Scp - Descr: SSH port on remote server Default: 22
*/
	Scp *Scp `yaml:"scp,omitempty"`

	/*Azure - Descr: Azure account name to access the storage service Default: <nil>
*/
	Azure *Azure `yaml:"azure,omitempty"`

	/*S3 - Descr: AWS Access Key to access the blobstore Default: <nil>
*/
	S3 *S3 `yaml:"s3,omitempty"`

}