package service_backup 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type ServiceBackupJob struct {

	/*ServiceBackup - Descr: SSH port on remote server Default: 22
*/
	ServiceBackup *ServiceBackup `yaml:"service-backup,omitempty"`

}