package syslog_drain_binder 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Loggregator struct {

	/*Etcd - Descr: PEM-encoded CA certificate Default: 
*/
	Etcd *LoggregatorEtcd `yaml:"etcd,omitempty"`

}