package syslog_drain_binder 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SyslogDrainBinderJob struct {

	/*MetronEndpoint - Descr: The host used to emit messages to the Metron agent Default: 127.0.0.1
*/
	MetronEndpoint *MetronEndpoint `yaml:"metron_endpoint,omitempty"`

	/*Loggregator - Descr: PEM-encoded CA certificate Default: 
*/
	Loggregator *Loggregator `yaml:"loggregator,omitempty"`

	/*Ssl - Descr: When connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*SystemDomain - Descr: Domain reserved for CF operator, base URL where the login, uaa, and other non-user apps listen Default: <nil>
*/
	SystemDomain interface{} `yaml:"system_domain,omitempty"`

	/*SyslogDrainBinder - Descr: Size (KB) of shell's locked memory limit. Set to 'kernel' to use the kernel's default. Non-numeric values other than 'kernel', 'soft', 'hard', and 'unlimited' will result in an error. Default: unlimited
*/
	SyslogDrainBinder *SyslogDrainBinder `yaml:"syslog_drain_binder,omitempty"`

	/*Cc - Descr: API URI of cloud controller Default: <nil>
*/
	Cc *Cc `yaml:"cc,omitempty"`

}