package send_email 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SendEmailJob struct {

	/*MysqlMonitoring - Descr: Secret of the UAA client used to send mysql monitoring notifications Default: <nil>
*/
	MysqlMonitoring *MysqlMonitoring `yaml:"mysql-monitoring,omitempty"`

	/*Domain - Descr: Domain reserved for CF operator, base URL where the login, uaa, and other non-user apps listen Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

	/*Ssl - Descr: specifies that the job is allowed to skip ssl cert verification Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}