package mysql 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysql struct {

	/*Mysql - Descr: Enable binlogs across all nodes Default: true
*/
	Mysql *Mysql `yaml:"mysql,omitempty"`

}