package mysql 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Mysql struct {

	/*AdminUsername - Descr: Username for the MySQL server admin user Default: root
*/
	AdminUsername interface{} `yaml:"admin_username,omitempty"`

	/*MaxHeapTableSize - Descr: The maximum size (in rows) to which user-created MEMORY tables are permitted to grow Default: 16777216
*/
	MaxHeapTableSize interface{} `yaml:"max_heap_table_size,omitempty"`

	/*InterruptNotifyCmd - Descr: Path to a binary to run when SST is prevented from running Default: 
*/
	InterruptNotifyCmd interface{} `yaml:"interrupt_notify_cmd,omitempty"`

	/*IbLogFileSize - Descr: Size of the ib_log_file used by innodb, in MB Default: 1024
*/
	IbLogFileSize interface{} `yaml:"ib_log_file_size,omitempty"`

	/*AdminPassword - Descr: Password for the MySQL server admin user Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

	/*DatabaseStartupTimeout - Descr: How long the startup script waits for the database to come online (in seconds) Default: <nil>
*/
	DatabaseStartupTimeout interface{} `yaml:"database_startup_timeout,omitempty"`

	/*DisableAutoSst - Descr: When disable_auto_sst is true, nodes unable to IST will be prevented from automatically deleting their data and performing an SST Default: true
*/
	DisableAutoSst interface{} `yaml:"disable_auto_sst,omitempty"`

	/*BinlogExpireDays - Descr: Time in days to store binlogs before purging Default: 60
*/
	BinlogExpireDays interface{} `yaml:"binlog_expire_days,omitempty"`

	/*SkipNameResolve - Descr: Do not restrict connections to database based on hostname Default: true
*/
	SkipNameResolve interface{} `yaml:"skip_name_resolve,omitempty"`

	/*SeededDatabases - Descr: Set of databases to seed Default: map[]
*/
	SeededDatabases interface{} `yaml:"seeded_databases,omitempty"`

	/*RoadminEnabled - Descr: Whether read only user is enabled Default: false
*/
	RoadminEnabled interface{} `yaml:"roadmin_enabled,omitempty"`

	/*ServerAuditExcludedUsers - Descr: Other database users to exclude from audit logging Default: []
*/
	ServerAuditExcludedUsers interface{} `yaml:"server_audit_excluded_users,omitempty"`

	/*Port - Descr: Port the mysql server should bind to Default: 3306
*/
	Port interface{} `yaml:"port,omitempty"`

	/*ClusterIps - Descr: List of nodes.  Must have the same number of ips as there are nodes in the cluster Default: <nil>
*/
	ClusterIps interface{} `yaml:"cluster_ips,omitempty"`

	/*WsrepDebug - Descr: When set to 1 or 2, the database server logs additional events surrounding errors to help in identifying and correcting problems. Note, these logs are written to disk and to syslog. Enabling this will possibly expose unencrypted application data. Default: 0
*/
	WsrepDebug interface{} `yaml:"wsrep_debug,omitempty"`

	/*ServerAuditEvents - Descr: Enable audit logging and specify types of events that will be logged. If null, then logging is disabled Default: <nil>
*/
	ServerAuditEvents interface{} `yaml:"server_audit_events,omitempty"`

	/*ServerAuditFileRotations - Descr: Number of audit file rotations to keep Default: 30
*/
	ServerAuditFileRotations interface{} `yaml:"server_audit_file_rotations,omitempty"`

	/*LogConflicts - Descr: Defines whether the node logs additional information about conflicts. The values that were in conflict are logged, so it is possible for user data to end up in the logs. Default: true
*/
	LogConflicts interface{} `yaml:"log_conflicts,omitempty"`

	/*TmpTableSize - Descr: The maximum size (in bytes) of internal in-memory temporary tables Default: 33554432
*/
	TmpTableSize interface{} `yaml:"tmp_table_size,omitempty"`

	/*MaxOpenFiles - Descr: Configure this number to be comfortably larger than the maximum number of tables you expect the database to support. Max is 104xxxx. Default: 65536
*/
	MaxOpenFiles interface{} `yaml:"max_open_files,omitempty"`

	/*ServerAuditFileRotateSizeInMb - Descr: Size in MB of each audit log file Default: 100
*/
	ServerAuditFileRotateSizeInMb interface{} `yaml:"server_audit_file_rotate_size_in_mb,omitempty"`

	/*WsrepMaxWsRows - Descr: Maximum permitted number of rows per writeset. Default: 131072
*/
	WsrepMaxWsRows interface{} `yaml:"wsrep_max_ws_rows,omitempty"`

	/*RoadminPassword - Descr: Password for the MySQL server read-only admin user Default: <nil>
*/
	RoadminPassword interface{} `yaml:"roadmin_password,omitempty"`

	/*ClusterHealth - Descr: Password for the cluster logger health user Default: <nil>
*/
	ClusterHealth *ClusterHealth `yaml:"cluster_health,omitempty"`

	/*MaxConnections - Descr: Maximum total number of database connections for the node Default: 1500
*/
	MaxConnections interface{} `yaml:"max_connections,omitempty"`

	/*WsrepMaxWsSize - Descr: Maximum permitted size in bytes per writeset. Default: 1073741824
*/
	WsrepMaxWsSize interface{} `yaml:"wsrep_max_ws_size,omitempty"`

	/*GcacheSize - Descr: Cache size used by galera (maximum amount of data possible in an IST), in MB Default: 512
*/
	GcacheSize interface{} `yaml:"gcache_size,omitempty"`

	/*BinlogEnabled - Descr: Enable binlogs across all nodes Default: true
*/
	BinlogEnabled interface{} `yaml:"binlog_enabled,omitempty"`

	/*InnodbBufferPoolSize - Descr: Optional, the size in bytes of the memory buffer InnoDB uses to cache data and indexes of its tables Default: <nil>
*/
	InnodbBufferPoolSize interface{} `yaml:"innodb_buffer_pool_size,omitempty"`

	/*GaleraHealthcheck - Descr: Port used by sidecar process to listen on Default: 9200
*/
	GaleraHealthcheck *GaleraHealthcheck `yaml:"galera_healthcheck,omitempty"`

}