package rejoin_unsafe 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Mysql struct {

	/*GaleraHealthcheck - Descr: Username used by the sidecar endpoints for Basic Auth Default: <nil>
*/
	GaleraHealthcheck *GaleraHealthcheck `yaml:"galera_healthcheck,omitempty"`

}