package rejoin_unsafe 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type RejoinUnsafeJob struct {

	/*CfMysql - Descr: Username used by the sidecar endpoints for Basic Auth Default: <nil>
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

	/*ClusterIps - Descr: IP addresses of all MySQL nodes Default: <nil>
*/
	ClusterIps interface{} `yaml:"cluster_ips,omitempty"`

}