package etcd_metrics_server 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdMetricsServerJob struct {

	/*EtcdMetricsServer - Descr: array of NATS addresses Default: <nil>
*/
	EtcdMetricsServer *EtcdMetricsServer `yaml:"etcd_metrics_server,omitempty"`

}