package etcd_proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdProxy struct {

	/*Etcd - Descr: etcd client certificate Default: 
*/
	Etcd *Etcd `yaml:"etcd,omitempty"`

	/*Port - Descr: port of proxy server Default: 4001
*/
	Port interface{} `yaml:"port,omitempty"`

}