package etcd_proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Etcd struct {

	/*CaCert - Descr: etcd ca certificate Default: 
*/
	CaCert interface{} `yaml:"ca_cert,omitempty"`

	/*ClientCert - Descr: etcd client certificate Default: 
*/
	ClientCert interface{} `yaml:"client_cert,omitempty"`

	/*ClientKey - Descr: etcd client key Default: 
*/
	ClientKey interface{} `yaml:"client_key,omitempty"`

	/*DnsSuffix - Descr: dns suffix of etcd server Default: etcd.service.cf.internal
*/
	DnsSuffix interface{} `yaml:"dns_suffix,omitempty"`

	/*Port - Descr: port of the etcd server Default: 4001
*/
	Port interface{} `yaml:"port,omitempty"`

}