package etcd_proxy 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type EtcdProxyJob struct {

	/*EtcdProxy - Descr: etcd client certificate Default: 
*/
	EtcdProxy *EtcdProxy `yaml:"etcd_proxy,omitempty"`

}