package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CloudController struct {

	/*AdminUser - Descr: Cloud Controller admin user Default: <nil>
*/
	AdminUser interface{} `yaml:"admin_user,omitempty"`

	/*AppsDomain - Descr: App domain that will be created Default: <nil>
*/
	AppsDomain interface{} `yaml:"apps_domain,omitempty"`

	/*AdminPassword - Descr: Cloud Controller admin user's password Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

	/*UseHttp - Descr: Flag for using HTTP when making application requests rather than the default HTTPS Default: false
*/
	UseHttp interface{} `yaml:"use_http,omitempty"`

	/*Api - Descr: URL of the Cloud Controller API Default: <nil>
*/
	Api interface{} `yaml:"api,omitempty"`

}