package acceptance_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TcpEmitter struct {

	/*OauthSecret - Descr: Password for UAA client for the tcp emitter. Default: <nil>
*/
	OauthSecret interface{} `yaml:"oauth_secret,omitempty"`

}