package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SmokeTestsJob struct {

	/*SmokeTests - Descr: The Elastic Runtime app name to use when running runtime tests Default: 
*/
	SmokeTests *SmokeTests `yaml:"smoke_tests,omitempty"`

}