package smoke_tests 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type SmokeTestsJob struct {

	/*SmokeTests - Descr: Ginkgo options for the smoke tests Default: 
*/
	SmokeTests *SmokeTests `yaml:"smoke_tests,omitempty"`

}