package test_restore 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type TestRestoreJob struct {

	/*CfMysql - Descr: Database port for contacting mysql Default: 3306
*/
	CfMysql *CfMysql `yaml:"cf_mysql,omitempty"`

	/*CfMysqlBackup - Descr: How long the errand will wait for the backup to get streamed to destination, in seconds Default: 400
*/
	CfMysqlBackup *CfMysqlBackup `yaml:"cf-mysql-backup,omitempty"`

	/*ServiceBackup - Descr: AWS Access Key to access the blobstore Default: <nil>
*/
	ServiceBackup *ServiceBackup `yaml:"service-backup,omitempty"`

}