package gorouter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type GorouterJob struct {

	/*RequestTimeoutInSeconds - Descr: Timeout in seconds for Router -> Endpoint roundtrip. Default: 900
*/
	RequestTimeoutInSeconds interface{} `yaml:"request_timeout_in_seconds,omitempty"`

	/*Router - Descr: Username for HTTP basic auth to the varz/status endpoint. Default: <nil>
*/
	Router *Router `yaml:"router,omitempty"`

	/*Nats - Descr:  Default: <nil>
*/
	Nats *Nats `yaml:"nats,omitempty"`

	/*Metron - Descr: The port used to emit dropsonde messages to the Metron agent. Default: 3457
*/
	Metron *Metron `yaml:"metron,omitempty"`

	/*RoutingApi - Descr: When false, Routing API requires OAuth tokens for authentication. Default: false
*/
	RoutingApi *RoutingApi `yaml:"routing_api,omitempty"`

	/*Uaa - Descr:  Default: 
*/
	Uaa *Uaa `yaml:"uaa,omitempty"`

}