package gorouter 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Status struct {

	/*Port - Descr: Port for the /health, /varz, and /routes endpoints. Default: 8080
*/
	Port interface{} `yaml:"port,omitempty"`

	/*User - Descr: Username for HTTP basic auth to the /varz and /routes endpoints. Default: <nil>
*/
	User interface{} `yaml:"user,omitempty"`

	/*Password - Descr: Password for HTTP basic auth to the /varz and /routes endpoints. Default: <nil>
*/
	Password interface{} `yaml:"password,omitempty"`

}