package canary 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CanaryJob struct {

	/*Diego - Descr: The Elastic Runtime space name to use for the canary app Default: <nil>
*/
	Diego *Diego `yaml:"diego,omitempty"`

}