package metron_agent 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type MetronAgentJob struct {

	/*MetronAgent - Descr: PEM-encoded client key Default: 
*/
	MetronAgent *MetronAgent `yaml:"metron_agent,omitempty"`

	/*Loggregator - Descr: IPs pointing to the ETCD cluster Default: <nil>
*/
	Loggregator *Loggregator `yaml:"loggregator,omitempty"`

	/*SyslogDaemonConfig - Descr: TCP port of syslog aggregator Default: <nil>
*/
	SyslogDaemonConfig *SyslogDaemonConfig `yaml:"syslog_daemon_config,omitempty"`

	/*MetronEndpoint - Descr: Shared secret used to verify cryptographically signed dropsonde messages Default: <nil>
*/
	MetronEndpoint *MetronEndpoint `yaml:"metron_endpoint,omitempty"`

}