package streaming_mysql_backup_tool 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type CfMysqlBackup struct {

	/*EndpointCredentials - Descr: Username used by backup client to stream a backup from the mysql node Default: <nil>
*/
	EndpointCredentials *EndpointCredentials `yaml:"endpoint_credentials,omitempty"`

	/*Ulimit - Descr: Maximum concurrent number of open files Default: 65536
*/
	Ulimit interface{} `yaml:"ulimit,omitempty"`

	/*BackupServer - Descr: Port number used for listening for backup requests Default: 8081
*/
	BackupServer *BackupServer `yaml:"backup-server,omitempty"`

}