package push_pivotal_account 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type AppPush struct {

	/*Timeout - Descr: App Push timeout for the Pivotal Account Application Default: 180
*/
	Timeout interface{} `yaml:"timeout,omitempty"`

	/*InstanceNumber - Descr: Number of instances for Pivotal Account Application Default: 1
*/
	InstanceNumber interface{} `yaml:"instance_number,omitempty"`

	/*Memory - Descr: App Push Memory limit for the Pivotal Account Application Default: 512
*/
	Memory interface{} `yaml:"memory,omitempty"`

}