package push_pivotal_account 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Cf struct {

	/*AdminUsername - Descr: Username of the CF admin user Default: <nil>
*/
	AdminUsername interface{} `yaml:"admin_username,omitempty"`

	/*AdminPassword - Descr: Password of the CF admin user Default: <nil>
*/
	AdminPassword interface{} `yaml:"admin_password,omitempty"`

	/*Org - Descr: CloudFoundry org Default: system
*/
	Org interface{} `yaml:"org,omitempty"`

	/*Domain - Descr: CloudFoundry system domain Default: <nil>
*/
	Domain interface{} `yaml:"domain,omitempty"`

}