package push_pivotal_account 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type GenericWhiteLabelConfigJson struct {

	/*CompanyName - Descr: Company Name Default: Pivotal
*/
	CompanyName interface{} `yaml:"companyName,omitempty"`

	/*LegalText - Descr:  Default: ©2016 Pivotal Software, Inc. All Rights Reserved.
*/
	LegalText interface{} `yaml:"legalText,omitempty"`

	/*SmallSquare - Descr: Square Logo/Favicon Default: /images/pivotal-logo-mobile.png
*/
	SmallSquare interface{} `yaml:"smallSquare,omitempty"`

	/*LegalLinks - Descr: Footer Links Default: [map[name:Privacy Policy href:https://run.pivotal.io/policies/privacy-policy/] map[name:Terms of Service href:https://run.pivotal.io/policies/terms-of-service]]
*/
	LegalLinks interface{} `yaml:"legalLinks,omitempty"`

	/*Logo - Descr: Main Logo Default: /images/pivotal_logo.png
*/
	Logo interface{} `yaml:"logo,omitempty"`

}