package push_pivotal_account 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Newrelic struct {

	/*AppName - Descr: NewRelic App Name to be set as environment variable in the pivotal account app Default: Pivotal Account
*/
	AppName interface{} `yaml:"app_name,omitempty"`

	/*ServiceName - Descr: NewRelic Service Name Default: 
*/
	ServiceName interface{} `yaml:"service_name,omitempty"`

}