package push_pivotal_account 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type PivotalAccount struct {

	/*AppPush - Descr: App Push Memory limit for the Pivotal Account Application Default: 512
*/
	AppPush *AppPush `yaml:"app_push,omitempty"`

	/*NotificationsUiLocation - Descr: Full URL of the notifications UI Default: <nil>
*/
	NotificationsUiLocation interface{} `yaml:"notifications_ui_location,omitempty"`

	/*NotificationsLocation - Descr: Full URL of the notifications API Default: <nil>
*/
	NotificationsLocation interface{} `yaml:"notifications_location,omitempty"`

	/*ClientSecret - Descr: UAA client secret for Pivotal Account Default: <nil>
*/
	ClientSecret interface{} `yaml:"client_secret,omitempty"`

	/*Route - Descr: The base route to the deployment of Pivotal Account Default: <nil>
*/
	Route interface{} `yaml:"route,omitempty"`

	/*UaaLocation - Descr: UAA location Default: <nil>
*/
	UaaLocation interface{} `yaml:"uaa_location,omitempty"`

	/*EnableGoogleAnalytics - Descr: Feature flag for google analytics Default: false
*/
	EnableGoogleAnalytics interface{} `yaml:"enable_google_analytics,omitempty"`

	/*ClientId - Descr: UAA client id for Pivotal Account Default: account
*/
	ClientId interface{} `yaml:"client_id,omitempty"`

}