package push_pivotal_account 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type PushPivotalAccountJob struct {

	/*PivotalAccount - Descr: The base route to the deployment of Pivotal Account Default: <nil>
*/
	PivotalAccount *PivotalAccount `yaml:"pivotal_account,omitempty"`

	/*Ssl - Descr: when connecting over TLS, do not verify certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

	/*Newrelic - Descr: NewRelic Service Name Default: 
*/
	Newrelic *Newrelic `yaml:"newrelic,omitempty"`

	/*GenericWhiteLabelConfigJson - Descr: Main Logo Default: /images/pivotal_logo.png
*/
	GenericWhiteLabelConfigJson *GenericWhiteLabelConfigJson `yaml:"generic_white_label_config_json,omitempty"`

	/*Cf - Descr: CloudFoundry system domain Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

}