package push_pivotal_account 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Ssl struct {

	/*SkipCertVerify - Descr: when connecting over TLS, do not verify certificates Default: false
*/
	SkipCertVerify interface{} `yaml:"skip_cert_verify,omitempty"`

}