package rep 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type Diego struct {

	/*Executor - Descr: Maximum number of concurrent delete container operations. Default: 32
*/
	Executor *Executor `yaml:"executor,omitempty"`

	/*Rep - Descr: PEM-encoded CA certificate Default: <nil>
*/
	Rep *Rep `yaml:"rep,omitempty"`

	/*Ssl - Descr: when connecting over https, ignore bad ssl certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}