package push_apps_manager 
/*
* File Generated by enaml generator
* !!! Please do not edit this file !!!
*/
type PushAppsManagerJob struct {

	/*Services - Descr: Cloud Foundry UAA server URL Default: <nil>
*/
	Services *Services `yaml:"services,omitempty"`

	/*Env - Descr: White labeling for marketplace name Default: Marketplace
*/
	Env *Env `yaml:"env,omitempty"`

	/*AppUsageService - Descr: Whether or not to allow viewing logs Default: false
*/
	AppUsageService *AppUsageService `yaml:"app_usage_service,omitempty"`

	/*Databases - Descr: Password credential for the app usage service Default: <nil>
*/
	Databases *Databases `yaml:"databases,omitempty"`

	/*Cf - Descr: Cloud Foundry apps domain, used for default app domains Default: <nil>
*/
	Cf *Cf `yaml:"cf,omitempty"`

	/*Ssl - Descr: when connecting over TLS, don't verify certificates Default: false
*/
	Ssl *Ssl `yaml:"ssl,omitempty"`

}